# -*- coding: utf-8 -*-
require "colorize"
require 'command_line/global'

task :default do
  system "rake -T"
end

require 'FileUtils'
desc "rename screen shot" #desc -> description
task :rename_screen_shot do # any name on task_name
  Dir.glob('./スクリーンショット*.png').each do |file|
    str=file.split(" ")
    trg=['screen_shot',str[1], str[2]].join('_')
    FileUtils.mv(file, trg, verbose: true)
  end
end
